[package]
name = "unix_socket"
version = "0.4.6"
authors = ["Steven Fackler <sfackler@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Unix domain socket bindings"
repository = "https://github.com/rust-lang-nursery/unix-socket"
documentation = "https://doc.rust-lang.org/unix-socket/doc/v0.4.6/unix_socket"
readme = "README.md"
keywords = ["posix", "unix", "socket", "domain"]
build = "build.rs"

[dependencies]
libc = "0.1"
debug-builders = "0.1"

[build-dependencies]
gcc = "0.3"

[dev-dependencies]
tempdir = "0.3"

[features]
default = ["from_raw_fd", "sendmsg"]

from_raw_fd = []
socket_timeout = []
sendmsg = []
